import re
from typing import Dict, Tuple, Optional


# Comprehensive mapping of known brand names, services, and semantic financial concepts
# Format: (category_slug, subcategory, confidence)
# Multi-word and more specific expressions are ordered first so they take precedence.
MERCHANT_RULES: Dict[str, Tuple[str, str, float]] = {
    # 1. Dining & Restaurants / Food Delivery (multi-word first)
    "uber eats": ("dining-restaurants", "Food Delivery", 0.98),
    "ubereats": ("dining-restaurants", "Food Delivery", 0.98),
    "swiggy instamart": ("groceries", "Quick Commerce", 0.98),
    "swiggy": ("dining-restaurants", "Food Delivery", 0.98),
    "zomato": ("dining-restaurants", "Food Delivery", 0.98),
    "doordash": ("dining-restaurants", "Food Delivery", 0.98),
    "food delivery": ("dining-restaurants", "Food Delivery", 0.96),
    "starbucks": ("dining-restaurants", "Coffee Shop", 0.98),
    "blue tokai": ("dining-restaurants", "Coffee Shop", 0.95),
    "cafe coffee day": ("dining-restaurants", "Coffee Shop", 0.95),
    "dunkin": ("dining-restaurants", "Coffee Shop", 0.95),
    "mcdonald's": ("dining-restaurants", "Fast Food", 0.98),
    "mcdonalds": ("dining-restaurants", "Fast Food", 0.98),
    "kfc": ("dining-restaurants", "Fast Food", 0.98),
    "domino's": ("dining-restaurants", "Fast Food", 0.98),
    "dominos": ("dining-restaurants", "Fast Food", 0.98),
    "burger king": ("dining-restaurants", "Fast Food", 0.98),
    "subway": ("dining-restaurants", "Fast Food", 0.95),
    "chipotle": ("dining-restaurants", "Fast Food", 0.98),
    "taco bell": ("dining-restaurants", "Fast Food", 0.98),
    "barbeque nation": ("dining-restaurants", "Restaurant", 0.95),
    "behrouz": ("dining-restaurants", "Food Delivery", 0.95),
    "baskin robbins": ("dining-restaurants", "Dessert", 0.95),
    "restaurant": ("dining-restaurants", "Restaurant", 0.95),
    "dinner": ("dining-restaurants", "Restaurant & Dining", 0.95),
    "lunch": ("dining-restaurants", "Restaurant & Dining", 0.95),
    "breakfast": ("dining-restaurants", "Restaurant & Dining", 0.95),
    "pizza": ("dining-restaurants", "Fast Food", 0.95),
    "burger": ("dining-restaurants", "Fast Food", 0.95),
    "biryani": ("dining-restaurants", "Restaurant & Dining", 0.95),

    # 2. Entertainment & Leisure (Movies, Cinema, Gaming, Events)
    "movie ticket": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "movie tickets": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "movie": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "movies": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "cinema": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "theatre": ("entertainment-leisure", "Movies / Cinema", 0.96),
    "theater": ("entertainment-leisure", "Movies / Cinema", 0.96),
    "film": ("entertainment-leisure", "Movies / Cinema", 0.95),
    "multiplex": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "pvr": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "inox": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "amc": ("entertainment-leisure", "Movies / Cinema", 0.96),
    "cinepolis": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "bookmyshow": ("entertainment-leisure", "Movies / Cinema", 0.98),
    "steam game": ("entertainment-leisure", "Video Games", 0.98),
    "steam": ("entertainment-leisure", "Video Games", 0.98),
    "playstation": ("entertainment-leisure", "Video Games", 0.98),
    "ps5": ("entertainment-leisure", "Video Games", 0.98),
    "nintendo": ("entertainment-leisure", "Video Games", 0.98),
    "xbox": ("entertainment-leisure", "Video Games", 0.98),
    "video game": ("entertainment-leisure", "Video Games", 0.98),
    "game": ("entertainment-leisure", "Video Games", 0.96),
    "gaming": ("entertainment-leisure", "Video Games", 0.96),
    "concert": ("entertainment-leisure", "Live Events", 0.96),
    "festival": ("entertainment-leisure", "Live Events", 0.95),
    "bowling": ("entertainment-leisure", "Amusement & Hobbies", 0.95),
    "arcade": ("entertainment-leisure", "Amusement & Hobbies", 0.95),

    # 3. Transportation & Fuel
    "uber ride": ("transportation-fuel", "Ride Sharing", 0.98),
    "uber": ("transportation-fuel", "Ride Sharing", 0.96),
    "ola cab": ("transportation-fuel", "Ride Sharing", 0.98),
    "ola": ("transportation-fuel", "Ride Sharing", 0.96),
    "lyft ride": ("transportation-fuel", "Ride Sharing", 0.98),
    "lyft": ("transportation-fuel", "Ride Sharing", 0.96),
    "rapido": ("transportation-fuel", "Ride Sharing", 0.96),
    "cab fare": ("transportation-fuel", "Ride Sharing", 0.96),
    "taxi": ("transportation-fuel", "Ride Sharing", 0.95),
    "ride": ("transportation-fuel", "Ride Sharing", 0.92),
    "indian oil": ("transportation-fuel", "Fuel", 0.98),
    "bharat petroleum": ("transportation-fuel", "Fuel", 0.98),
    "hpcl": ("transportation-fuel", "Fuel", 0.98),
    "petrol": ("transportation-fuel", "Fuel", 0.98),
    "diesel": ("transportation-fuel", "Fuel", 0.98),
    "fuel": ("transportation-fuel", "Fuel", 0.96),
    "gas station": ("transportation-fuel", "Fuel", 0.96),
    "shell": ("transportation-fuel", "Fuel", 0.95),
    "chevron": ("transportation-fuel", "Fuel", 0.98),
    "irctc": ("transportation-fuel", "Rail Travel", 0.98),
    "train ticket": ("transportation-fuel", "Rail Travel", 0.98),
    "fastag": ("transportation-fuel", "Tolls", 0.98),
    "toll": ("transportation-fuel", "Tolls", 0.96),
    "metro": ("transportation-fuel", "Public Transit", 0.95),
    "parking": ("transportation-fuel", "Parking", 0.95),

    # 4. Groceries
    "reliance fresh": ("groceries", "Supermarket", 0.98),
    "blinkit": ("groceries", "Quick Commerce", 0.98),
    "zepto": ("groceries", "Quick Commerce", 0.98),
    "instamart": ("groceries", "Quick Commerce", 0.98),
    "bigbasket": ("groceries", "Online Supermarket", 0.98),
    "dmart": ("groceries", "Supermarket", 0.98),
    "whole foods": ("groceries", "Supermarket", 0.98),
    "trader joe's": ("groceries", "Supermarket", 0.98),
    "costco": ("groceries", "Wholesale Club", 0.95),
    "walmart": ("groceries", "Supermarket", 0.92),
    "nature's basket": ("groceries", "Supermarket", 0.95),
    "groceries": ("groceries", "Groceries", 0.98),
    "grocery": ("groceries", "Groceries", 0.98),
    "supermarket": ("groceries", "Supermarket", 0.96),
    "vegetables": ("groceries", "Produce", 0.96),
    "fruits": ("groceries", "Produce", 0.96),
    "milk": ("groceries", "Dairy", 0.95),

    # 5. Utilities & Bills
    "electricity bill": ("utilities-bills", "Electricity", 0.98),
    "electricity": ("utilities-bills", "Electricity", 0.98),
    "electric bill": ("utilities-bills", "Electricity", 0.98),
    "power bill": ("utilities-bills", "Electricity", 0.98),
    "bescom": ("utilities-bills", "Electricity", 0.98),
    "tata power": ("utilities-bills", "Electricity", 0.98),
    "water bill": ("utilities-bills", "Water", 0.98),
    "water utility": ("utilities-bills", "Water", 0.98),
    "gas bill": ("utilities-bills", "Gas", 0.98),
    "piped gas": ("utilities-bills", "Gas", 0.98),
    "indane": ("utilities-bills", "Cooking Gas", 0.98),
    "lpg cylinder": ("utilities-bills", "Cooking Gas", 0.98),
    "internet bill": ("utilities-bills", "Internet", 0.98),
    "broadband": ("utilities-bills", "Internet", 0.98),
    "wifi": ("utilities-bills", "Internet", 0.96),
    "act fibernet": ("utilities-bills", "Internet", 0.98),
    "xfinity": ("utilities-bills", "Internet", 0.98),
    "comcast": ("utilities-bills", "Internet", 0.98),
    "airtel": ("utilities-bills", "Mobile Phone", 0.96),
    "jio": ("utilities-bills", "Mobile Phone", 0.96),
    "verizon": ("utilities-bills", "Mobile Phone", 0.98),
    "t-mobile": ("utilities-bills", "Mobile Phone", 0.98),
    "mobile recharge": ("utilities-bills", "Mobile Phone", 0.96),
    "utility bill": ("utilities-bills", "Utility Bills", 0.95),
    "utility": ("utilities-bills", "Utility Bills", 0.95),

    # 6. Subscriptions & Software
    "netflix subscription": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "netflix": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "spotify": ("subscriptions-software", "Audio Streaming", 0.98),
    "apple music": ("subscriptions-software", "Audio Streaming", 0.98),
    "disney plus": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "disney": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "hotstar": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "youtube premium": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "amazon prime": ("subscriptions-software", "Digital Subscription", 0.95),
    "prime video": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "hbo": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "hulu": ("subscriptions-software", "Streaming Entertainment", 0.98),
    "chatgpt": ("subscriptions-software", "AI & Software", 0.98),
    "openai": ("subscriptions-software", "AI & Software", 0.98),
    "github": ("subscriptions-software", "Developer Tools", 0.98),
    "aws": ("subscriptions-software", "Cloud Hosting", 0.95),
    "digitalocean": ("subscriptions-software", "Cloud Hosting", 0.98),
    "adobe": ("subscriptions-software", "Creative Software", 0.98),
    "notion": ("subscriptions-software", "Productivity Software", 0.98),
    "midjourney": ("subscriptions-software", "AI & Software", 0.98),
    "microsoft 365": ("subscriptions-software", "Productivity Software", 0.98),
    "subscription": ("subscriptions-software", "Software & Services", 0.95),

    # 7. Shopping & Retail
    "amazon": ("shopping-retail", "E-Commerce", 0.95),
    "flipkart": ("shopping-retail", "E-Commerce", 0.95),
    "myntra": ("shopping-retail", "Apparel", 0.98),
    "zara": ("shopping-retail", "Apparel", 0.98),
    "h&m": ("shopping-retail", "Apparel", 0.98),
    "nike": ("shopping-retail", "Footwear", 0.98),
    "adidas": ("shopping-retail", "Footwear", 0.98),
    "clothing": ("shopping-retail", "Apparel", 0.95),
    "clothes": ("shopping-retail", "Apparel", 0.95),
    "shoes": ("shopping-retail", "Footwear", 0.95),
    "ikea": ("shopping-retail", "Home & Furniture", 0.98),
    "decathlon": ("shopping-retail", "Sporting Goods", 0.98),
    "sephora": ("shopping-retail", "Beauty & Personal Care", 0.98),
    "nykaa": ("shopping-retail", "Beauty & Personal Care", 0.98),
    "shopping": ("shopping-retail", "Shopping & Retail", 0.92),

    # 8. Healthcare & Medical
    "apollo pharmacy": ("healthcare-medical", "Pharmacy", 0.98),
    "apollo": ("healthcare-medical", "Pharmacy", 0.95),
    "cvs pharmacy": ("healthcare-medical", "Pharmacy", 0.98),
    "cvs": ("healthcare-medical", "Pharmacy", 0.98),
    "walgreens": ("healthcare-medical", "Pharmacy", 0.98),
    "medplus": ("healthcare-medical", "Pharmacy", 0.98),
    "medicine": ("healthcare-medical", "Pharmacy", 0.96),
    "pharmacy": ("healthcare-medical", "Pharmacy", 0.96),
    "doctor": ("healthcare-medical", "Doctor Consultation", 0.96),
    "hospital": ("healthcare-medical", "Hospital Care", 0.96),
    "clinic": ("healthcare-medical", "Doctor Consultation", 0.95),
    "cult.fit": ("healthcare-medical", "Fitness & Gym", 0.98),
    "equinox": ("healthcare-medical", "Fitness & Gym", 0.98),
    "gym": ("healthcare-medical", "Fitness & Gym", 0.95),

    # 9. Education & Learning
    "udemy": ("education-learning", "Online Courses", 0.98),
    "coursera": ("education-learning", "Online Courses", 0.98),
    "tuition": ("education-learning", "Tuition", 0.98),
    "school fee": ("education-learning", "School Fees", 0.98),
    "college": ("education-learning", "College & Tuition", 0.95),
    "course": ("education-learning", "Online Courses", 0.95),
    "books": ("education-learning", "Books", 0.95),

    # 10. Travel & Vacation
    "flight ticket": ("travel-vacation", "Airlines", 0.98),
    "flight": ("travel-vacation", "Airlines", 0.98),
    "indigo": ("travel-vacation", "Airlines", 0.98),
    "delta": ("travel-vacation", "Airlines", 0.95),
    "air india": ("travel-vacation", "Airlines", 0.98),
    "marriott": ("travel-vacation", "Lodging", 0.98),
    "airbnb": ("travel-vacation", "Lodging", 0.98),
    "hilton": ("travel-vacation", "Lodging", 0.98),
    "hotel": ("travel-vacation", "Lodging", 0.96),
    "makemytrip": ("travel-vacation", "Travel Agency", 0.98),
    "booking.com": ("travel-vacation", "Lodging", 0.98),

    # 11. Salary & Wages (Income)
    "salary": ("salary-wages", "Paycheck", 0.98),
    "payroll": ("salary-wages", "Paycheck", 0.98),
    "paycheck": ("salary-wages", "Paycheck", 0.98),
    "bonus": ("salary-wages", "Bonus", 0.96),
    "stipend": ("salary-wages", "Paycheck", 0.96),
    "freelance": ("freelance-consulting", "Freelance Invoice", 0.96),
    "dividend": ("dividends", "Stock Dividends", 0.98),
}

# Category slug to clean readable display name
CATEGORY_NAMES: Dict[str, str] = {
    "dining-restaurants": "Dining & Restaurants",
    "groceries": "Groceries",
    "transportation-fuel": "Transportation & Fuel",
    "utilities-bills": "Utilities & Bills",
    "subscriptions-software": "Subscriptions & Software",
    "shopping-retail": "Shopping & Retail",
    "healthcare-medical": "Healthcare & Medical",
    "entertainment-leisure": "Entertainment & Leisure",
    "housing-rent": "Housing & Rent",
    "travel-vacation": "Travel & Vacation",
    "education-learning": "Education & Learning",
    "salary-wages": "Salary & Wages",
    "freelance-consulting": "Freelance & Consulting",
    "investment-income": "Investment Income",
    "dividends": "Dividends",
    "other-income": "Other Income",
    "financial-fees": "Financial & Bank Fees",
}


def lookup_merchant_rule(text: str) -> Optional[Tuple[str, str, float]]:
    """Match input text against deterministic high-confidence merchant and semantic domain rules.

    Returns (category_slug, subcategory, confidence) if matched, else None.
    Uses word boundary regex to prevent partial match false positives.
    """
    if not isinstance(text, str) or not text.strip():
        return None
    lower = text.lower()
    for keyword, rule in MERCHANT_RULES.items():
        pattern = rf"\b{re.escape(keyword)}\b"
        if re.search(pattern, lower):
            return rule

    return None

